### ISSUE TITLE
Mouse scroll not smooth

### ISSUE THREAD

**Issue by eva7sk** [ergoemacs/ergoemacs-mode#430] opened 2016-10-06 16:12 UTC

**Comment by eva7sk** [comment] 2016-10-11 03:13
Can't Double Click to select word

**Comment by eva7sk** [comment] 2016-10-11 03:15
Emacs 25.1 / Git

**Comment by mattfidler** [comment] 2016-10-12 19:54
Mouse handling and command loop changed with Emacs 25.1, I'm not sure what you mean by mouse-scroll not smooth, though.  I can verify that I cannot double click to select a word...

There are a few more issues that I have noticed that were not there with emacs 24. Including having the point within hidden/folded sections of an org-mode buffer.

**Comment by jn287** [comment] 2016-11-04 15:46
I'm also having problems with the mouse scrolling which could possibly be the same issue. When I scroll with the mouse wheel it only moves 5 lines forward no matter how long i scroll. To scroll more than 5 lines i have to either stop scrolling for half a second and then continue to move another 5 lines forward, or I have to move the mouse pointer by a small amount. If I exit ergoemacs-mode mouse scrolling works without issues. I'm using emacs 24.5.1 and ergoemacs from melpa.

**Comment by mattfidler** [comment] 2016-11-04 23:18
I am not sure why.  I cannot reproduce this behavior in windows.

**Comment by mattfidler** [comment] 2016-11-22 17:31
I changed the way the ergoemacs-mode handles mouse commands, so this should be fixed.  I'm unsure.  Could someone test?

**Comment by mattfidler** [comment] 2016-11-24 04:01
It should not touch mouse commands any more.  Let me know if you see the issue again.

**Closed by mattfidler** 2016-11-24 04:01 UTC
Labels: bug
