### ISSUE TITLE
Ergoemacs-mode + helm : Args out of range: #<buffer helm M-x>, 0, 1

### ISSUE THREAD

**Issue by alexei28** [ergoemacs/ergoemacs-mode#443] opened 2016-11-21 08:00 UTC
Windows 7 (64 bit)
Emacs 24.5
ergoemacs-mode-20161025.1222
helm-20161116.1211
helm-core-20161113.908

in init.el
;; ergoemacs-mode package
(add-to-list 'load-path "~/.emacs.d/elpa/ergoemacs-mode-20161025.1222/")
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) 
(setq ergoemacs-keyboard-layout "us") 
(ergoemacs-mode 1)

;; helm package
(require 'helm)
(require 'helm-config)
(helm-mode 1)
(global-set-key (kbd "M-x") 'helm-M-x)

1.Start emacs
2.Press M-x or M-a
3. In minibuffer show error : **Args out of range: #<buffer helm M-x>, 0, 1**
4. Again press M-x or M-a
5. Success show Emacs command in buffer *helm M-x*

**Comment by mattfidler** [comment] 2016-11-24 02:14
Duplicate of #438

**Closed by mattfidler** 2016-11-24 02:14 UTC
